### PR TITLE
Run Cypress tests for push events and pull requests targeting main branch

### PR DESCRIPTION
**Pull request by OssamaRafique**
This PR adds a GitHub Actions workflow to run Cypress tests for both push events and pull requests created against the `main` branch. The workflow is configured to run on an Ubuntu environment with Node.js 14.x. It checks out the repository, installs the dependencies using Yarn, and runs the Cypress tests.

By running Cypress tests on both push events and pull requests, we can ensure that our code changes do not break existing functionality and maintain a high level of code quality.

### CODE REVIEW

**Comment by jkanche** [comment]
damn we think alike ;) i was about to do this #56

**Comment by OssamaRafique** [comment]
I missed to push package.json. Will push it now to fix this.

**Comment by OssamaRafique** [comment]
> This is a good idea, but IIRC some of the tests are flaky. Particularly [ones](https://github.com/epiviz/epiviz.gl/blob/main/cypress/integration/expected-images.spec.js#L24) that do a "render and check". These may need to be marked as such to prevent some annoying fails.

I added fixes for other unit tests here #60 for render and check tests, I replaced assertions with console warnings.

**Comment by jkanche** [comment]
@OssamaRafique 

- [ ] merge the changes from master to this branch (the recent PR)
- [ ] one of the tests seem to be failing

**Comment by SamGRosen** [comment]
These tests should be skipped as they are only meant for recording correct answers: `record-tests.spec.js`

**Pull request merged**
